INFO     utils.webdriver_factory:webdriver_factory.py:90 Detected Docker environment - using web:8000
INFO     utils.webdriver_factory:webdriver_factory.py:156 Creating chrome latest WebDriver with remote=True, remote_url=http://selenoid:4444/wd/hub
WARNING  utils.webdriver_factory:webdriver_factory.py:121 Error connecting to Selenoid: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /status (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd04dfaf700>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
WARNING  utils.webdriver_factory:webdriver_factory.py:162 Could not verify Selenoid connection at http://selenoid:4444/wd/hub
WARNING  utils.webdriver_factory:webdriver_factory.py:163 Proceeding anyway, but this might cause issues
INFO     utils.webdriver_factory:webdriver_factory.py:314 Connecting to Selenoid at http://selenoid:4444/wd/hub with Chrome latest
ERROR    utils.webdriver_factory:webdriver_factory.py:321 Failed to create Remote WebDriver: Message: wait: http://172.17.0.4:4444/ does not respond in 30s

INFO     utils.webdriver_factory:webdriver_factory.py:326 Selenoid status response: 200
INFO     utils.webdriver_factory:webdriver_factory.py:327 Response content: b'{"total":8,"used":0,"queued":0,"pending":1,"browsers":{"chrome":{"latest":{}}}}\n'...
ERROR    utils.webdriver_factory:webdriver_factory.py:201 Failed to create WebDriver: Message: wait: http://172.17.0.4:4444/ does not respond in 30s