2025-02-28 01:37:33,779 - utils.webdriver_factory - INFO - Detected Docker environment - using web:8000
2025-02-28 01:37:33,842 - utils.webdriver_factory - INFO - Creating chrome latest WebDriver with remote=True, remote_url=http://selenoid:4444/wd/hub
2025-02-28 01:37:33,843 - utils.webdriver_factory - WARNING - Error connecting to Selenoid: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3aa547730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-28 01:37:33,844 - utils.webdriver_factory - WARNING - Could not verify Selenoid connection at http://selenoid:4444/wd/hub
2025-02-28 01:37:33,844 - utils.webdriver_factory - WARNING - Proceeding anyway, but this might cause issues
2025-02-28 01:37:33,844 - utils.webdriver_factory - INFO - Connecting to Selenoid at http://selenoid:4444/wd/hub with Chrome latest
2025-02-28 01:37:33,845 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ab16c0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
2025-02-28 01:37:33,846 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ab16c280>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
2025-02-28 01:37:33,846 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ab16c4c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
2025-02-28 01:37:33,847 - utils.webdriver_factory - ERROR - Failed to create Remote WebDriver: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ab16c700>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-28 01:37:33,848 - utils.webdriver_factory - ERROR - Could not get Selenoid status: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ab16c820>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-28 01:37:33,848 - utils.webdriver_factory - ERROR - Failed to create WebDriver: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd3ab16c700>: Failed to establish a new connection: [Errno 111] Connection refused'))
