{"uid":"1b7b826fa6b61b24","name":"test_dashboard_acesso_nao_autenticado[chrome]","fullName":"tests.dashboard_acesso_não_autenticado_test#test_dashboard_acesso_nao_autenticado","historyId":"c2275a8979a5b604bd1438c9dec7cd21","time":{"start":1740707418427,"stop":1740707430023,"duration":11596},"description":"TP-14: Dashboard - Tentativa de Acesso Não Autenticado","descriptionHtml":"<p>TP-14: Dashboard - Tentativa de Acesso Não Autenticado</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x559f6589a0ca <unknown>\n#1 0x559f655662b0 <unknown>\n#2 0x559f655b5b22 <unknown>\n#3 0x559f655b5dc1 <unknown>\n#4 0x559f655fb994 <unknown>\n#5 0x559f655da92d <unknown>\n#6 0x559f655f8e26 <unknown>\n#7 0x559f655da6a3 <unknown>\n#8 0x559f655a84f3 <unknown>\n#9 0x559f655a94fe <unknown>\n#10 0x559f65860d7b <unknown>\n#11 0x559f65864d31 <unknown>\n#12 0x559f6584cc85 <unknown>\n#13 0x559f658658a2 <unknown>\n#14 0x559f65831e1f <unknown>\n#15 0x559f65888e48 <unknown>\n#16 0x559f65889013 <unknown>\n#17 0x559f65898ebc <unknown>\n#18 0x7ff3c68ecac3 <unknown>","statusTrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/app/tests/dashboard_acesso_não_autenticado_test.py\", line 39, in test_dashboard_acesso_nao_autenticado\n    dashboard_page.logout()\n  File \"/app/pages/dashboard_page.py\", line 39, in logout\n    self.click_element(*self.locators.navbar.LOGOUT_LINK)\n  File \"/app/pages/base_page.py\", line 57, in click_element\n    element = self.find_clickable_element(*locator, timeout=2)\n  File \"/app/pages/base_page.py\", line 35, in find_clickable_element\n    return self.wait_for_element(locator, timeout, EC.element_to_be_clickable)\n  File \"/app/pages/base_page.py\", line 22, in wait_for_element\n    return wait.until(condition(locator))\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 101, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x559f6589a0ca <unknown>\n#1 0x559f655662b0 <unknown>\n#2 0x559f655b5b22 <unknown>\n#3 0x559f655b5dc1 <unknown>\n#4 0x559f655fb994 <unknown>\n#5 0x559f655da92d <unknown>\n#6 0x559f655f8e26 <unknown>\n#7 0x559f655da6a3 <unknown>\n#8 0x559f655a84f3 <unknown>\n#9 0x559f655a94fe <unknown>\n#10 0x559f65860d7b <unknown>\n#11 0x559f65864d31 <unknown>\n#12 0x559f6584cc85 <unknown>\n#13 0x559f658658a2 <unknown>\n#14 0x559f65831e1f <unknown>\n#15 0x559f65888e48 <unknown>\n#16 0x559f65889013 <unknown>\n#17 0x559f65898ebc <unknown>\n#18 0x7ff3c68ecac3 <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"base_url","time":{"start":1740707336183,"stop":1740707336184,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1740707336184,"stop":1740707336184,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false},{"name":"pytestconfig","time":{"start":1740707336184,"stop":1740707336184,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false},{"name":"delete_output_dir","time":{"start":1740707336185,"stop":1740707336185,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false},{"name":"_session_faker","time":{"start":1740707336185,"stop":1740707336199,"duration":14},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false},{"name":"sensitive_url","time":{"start":1740707336199,"stop":1740707336203,"duration":4},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false},{"name":"remote_url","time":{"start":1740707336203,"stop":1740707336203,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false},{"name":"_skip_sensitive","time":{"start":1740707417032,"stop":1740707417032,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1740707417032,"stop":1740707418426,"duration":1394},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"TP-14: Dashboard - Tentativa de Acesso Não Autenticado","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x559f6589a0ca <unknown>\n#1 0x559f655662b0 <unknown>\n#2 0x559f655b5b22 <unknown>\n#3 0x559f655b5dc1 <unknown>\n#4 0x559f655fb994 <unknown>\n#5 0x559f655da92d <unknown>\n#6 0x559f655f8e26 <unknown>\n#7 0x559f655da6a3 <unknown>\n#8 0x559f655a84f3 <unknown>\n#9 0x559f655a94fe <unknown>\n#10 0x559f65860d7b <unknown>\n#11 0x559f65864d31 <unknown>\n#12 0x559f6584cc85 <unknown>\n#13 0x559f658658a2 <unknown>\n#14 0x559f65831e1f <unknown>\n#15 0x559f65888e48 <unknown>\n#16 0x559f65889013 <unknown>\n#17 0x559f65898ebc <unknown>\n#18 0x7ff3c68ecac3 <unknown>","statusTrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/app/tests/dashboard_acesso_não_autenticado_test.py\", line 39, in test_dashboard_acesso_nao_autenticado\n    dashboard_page.logout()\n  File \"/app/pages/dashboard_page.py\", line 39, in logout\n    self.click_element(*self.locators.navbar.LOGOUT_LINK)\n  File \"/app/pages/base_page.py\", line 57, in click_element\n    element = self.find_clickable_element(*locator, timeout=2)\n  File \"/app/pages/base_page.py\", line 35, in find_clickable_element\n    return self.wait_for_element(locator, timeout, EC.element_to_be_clickable)\n  File \"/app/pages/base_page.py\", line 22, in wait_for_element\n    return wait.until(condition(locator))\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 101, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x559f6589a0ca <unknown>\n#1 0x559f655662b0 <unknown>\n#2 0x559f655b5b22 <unknown>\n#3 0x559f655b5dc1 <unknown>\n#4 0x559f655fb994 <unknown>\n#5 0x559f655da92d <unknown>\n#6 0x559f655f8e26 <unknown>\n#7 0x559f655da6a3 <unknown>\n#8 0x559f655a84f3 <unknown>\n#9 0x559f655a94fe <unknown>\n#10 0x559f65860d7b <unknown>\n#11 0x559f65864d31 <unknown>\n#12 0x559f6584cc85 <unknown>\n#13 0x559f658658a2 <unknown>\n#14 0x559f65831e1f <unknown>\n#15 0x559f65888e48 <unknown>\n#16 0x559f65889013 <unknown>\n#17 0x559f65898ebc <unknown>\n#18 0x7ff3c68ecac3 <unknown>","steps":[{"name":"Make request to Faker API: http://faker:5000/generate/user","time":{"start":1740707418427,"stop":1740707418432,"duration":5},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false}],"attachments":[{"uid":"2afd6c7649750e5e","name":"dashboard_direct_access_attempt","source":"2afd6c7649750e5e.png","type":"image/png","size":42267},{"uid":"70ed6e29fe11ce20","name":"dashboard_after_authentication","source":"70ed6e29fe11ce20.png","type":"image/png","size":45260},{"uid":"c776262bc1f3a056","name":"element_not_found","source":"c776262bc1f3a056.png","type":"image/png","size":45260},{"uid":"5e9fb9c8ce8c9327","name":"click_failed","source":"5e9fb9c8ce8c9327.png","type":"image/png","size":45260},{"uid":"ae301ccfc3b537f9","name":"log","source":"ae301ccfc3b537f9.txt","type":"text/plain","size":1159},{"uid":"ab3c3a6d3a60f8d0","name":"stdout","source":"ab3c3a6d3a60f8d0.txt","type":"text/plain","size":1192}],"parameters":[],"stepsCount":1,"attachmentsCount":6,"shouldDisplayMessage":true,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1740707430025,"stop":1740707454951,"duration":24926},"status":"passed","steps":[],"attachments":[{"uid":"b7cc5be312931dbc","name":"failure_chrome_test_dashboard_acesso_nao_autenticado_chrome__20250228_015017","source":"b7cc5be312931dbc.png","type":"image/png","size":45260},{"uid":"82123c86c8af5192","name":"page_source_on_failure_chrome","source":"82123c86c8af5192.html","type":"text/html","size":4391}],"parameters":[],"stepsCount":0,"attachmentsCount":2,"shouldDisplayMessage":false,"hasContent":true,"attachmentStep":false}],"labels":[{"name":"story","value":"Unauthorized Access"},{"name":"feature","value":"Dashboard"},{"name":"epic","value":"Authentication"},{"name":"tag","value":"security"},{"name":"tag","value":"nondestructive"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"dashboard_acesso_não_autenticado_test"},{"name":"host","value":"e130d6c28101"},{"name":"thread","value":"1-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.dashboard_acesso_não_autenticado_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"selenium_browser","value":"'chrome'"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["security","nondestructive"]},"source":"1b7b826fa6b61b24.json","parameterValues":["'chrome'"]}