2025-02-28 00:47:37,605 - utils.webdriver_factory - INFO - Detected Docker environment - using web:8000
2025-02-28 00:47:37,626 - utils.webdriver_factory - INFO - Creating chrome latest WebDriver with remote=True, remote_url=http://selenoid:4444/wd/hub
2025-02-28 00:47:41,194 - utils.webdriver_factory - WARNING - Error connecting to Selenoid: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /status (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f14e02fbeb0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
2025-02-28 00:47:41,194 - utils.webdriver_factory - WARNING - Could not verify Selenoid connection at http://selenoid:4444/wd/hub
2025-02-28 00:47:41,194 - utils.webdriver_factory - WARNING - Proceeding anyway, but this might cause issues
2025-02-28 00:47:41,194 - utils.webdriver_factory - INFO - Connecting to Selenoid at http://selenoid:4444/wd/hub with Chrome latest
2025-02-28 00:47:44,726 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f14e02f9510>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)")': /wd/hub/session
2025-02-28 00:47:48,087 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f14e02f8d30>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)")': /wd/hub/session
2025-02-28 00:47:51,766 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f14e02f87c0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)")': /wd/hub/session
2025-02-28 00:47:55,227 - utils.webdriver_factory - ERROR - Failed to create Remote WebDriver: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f14e02fa680>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
2025-02-28 00:47:58,719 - utils.webdriver_factory - ERROR - Could not get Selenoid status: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /status (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f14e02f91b0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
2025-02-28 00:47:58,720 - utils.webdriver_factory - ERROR - Failed to create WebDriver: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f14e02fa680>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
