2025-02-28 00:46:42,355 - utils.webdriver_factory - INFO - Using localhost:8000 for application
2025-02-28 00:46:42,440 - utils.webdriver_factory - INFO - Creating chrome latest WebDriver with remote=True, remote_url=http://selenoid:4444/wd/hub
2025-02-28 00:46:45,926 - utils.webdriver_factory - WARNING - Error connecting to Selenoid: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /status (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcdfb98b0a0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
2025-02-28 00:46:45,926 - utils.webdriver_factory - WARNING - Could not verify Selenoid connection at http://selenoid:4444/wd/hub
2025-02-28 00:46:45,926 - utils.webdriver_factory - WARNING - Proceeding anyway, but this might cause issues
2025-02-28 00:46:45,927 - utils.webdriver_factory - INFO - Connecting to Selenoid at http://selenoid:4444/wd/hub with Chrome latest
2025-02-28 00:46:49,364 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcdfb988fa0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)")': /wd/hub/session
2025-02-28 00:46:52,973 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcdfb989780>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)")': /wd/hub/session
2025-02-28 00:46:56,417 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcdfb98b730>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)")': /wd/hub/session
2025-02-28 00:47:05,779 - utils.webdriver_factory - ERROR - Failed to create Remote WebDriver: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcdfb988cd0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
2025-02-28 00:47:09,255 - utils.webdriver_factory - ERROR - Could not get Selenoid status: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /status (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcdfb98b7c0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
2025-02-28 00:47:09,256 - utils.webdriver_factory - ERROR - Failed to create WebDriver: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcdfb988cd0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
