{"uuid": "7bfca905-277f-49af-92d8-d523fdc9b37a", "children": ["c4644a96-142c-426e-89bf-2314858148c1"], "befores": [{"name": "driver", "status": "failed", "statusDetails": {"message": "Failed: Could not initialize WebDriver for chrome: Message: wait: http://172.17.0.2:4444/ does not respond in 30s\n\n", "trace": "  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/app/conftest.py\", line 96, in driver\n    pytest.fail(f\"Could not initialize WebDriver for {selenium_browser}: {str(e)}\")\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "webdriver_exception_chrome", "source": "eb1a9dfc-dea5-46ec-b208-9cda5759ae4b-attachment.txt", "type": "text/plain"}], "start": 1740704061232, "stop": 1740704097444}], "start": 1740704061232, "stop": 1740704097447}