{"uuid": "87c493f9-ff6e-4e40-9466-d5405697af09", "children": ["81c118b6-51b8-4dea-af94-4bead9d3ded9"], "befores": [{"name": "driver", "status": "failed", "statusDetails": {"message": "Failed: Could not initialize WebDriver for chrome: Message: wait: http://172.17.0.4:4444/ does not respond in 30s\n\n", "trace": "  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/app/conftest.py\", line 96, in driver\n    pytest.fail(f\"Could not initialize WebDriver for {selenium_browser}: {str(e)}\")\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "webdriver_exception_chrome", "source": "85b7d2e8-96ff-4b55-9d38-4a5f9cd4aeea-attachment.txt", "type": "text/plain"}], "start": 1740704369846, "stop": 1740704409736}], "start": 1740704369846, "stop": 1740704409740}