{"uuid": "67f15d3c-cdde-431d-933e-d753eb7adfdc", "children": ["f5f0d63a-99aa-46e3-bbd9-8b960978b637"], "befores": [{"name": "driver", "status": "failed", "statusDetails": {"message": "Failed: Could not initialize WebDriver for chrome: Message: wait: http://172.17.0.2:4444/ does not respond in 30s\n\n", "trace": "  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/app/conftest.py\", line 96, in driver\n    pytest.fail(f\"Could not initialize WebDriver for {selenium_browser}: {str(e)}\")\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "webdriver_exception_chrome", "source": "0ee4f56f-824b-46be-b7f3-367d14154621-attachment.txt", "type": "text/plain"}], "start": 1740704372243, "stop": 1740704406828}], "start": 1740704372243, "stop": 1740704406831}