{"name": "test_login_credenciais_validas[chrome]", "status": "failed", "statusDetails": {"message": "AssertionError: User was not redirected to dashboard\nassert 'dashboard' in 'http://web:8000/accounts/login/'\n +  where 'http://web:8000/accounts/login/' = <selenium.webdriver.remote.webdriver.WebDriver (session=\"ac443b5c664c1a9a171333d9036ffc8d\")>.current_url", "trace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/app/tests/login_credenciais_validas_test.py\", line 49, in test_login_credenciais_validas\n    assert \"dashboard\" in driver.current_url, \"User was not redirected to dashboard\"\nAssertionError: User was not redirected to dashboard\nassert 'dashboard' in 'http://web:8000/accounts/login/'\n +  where 'http://web:8000/accounts/login/' = <selenium.webdriver.remote.webdriver.WebDriver (session=\"ac443b5c664c1a9a171333d9036ffc8d\")>.current_url"}, "description": "\n    TP-1: Login - Credenciais Validas\n    \n    Objetivo:\n    - Verificar se o login ocorre com sucesso quando as credenciais estão corretas.\n    - Garantir que o usuário é redirecionado à página principal ou dashboard.\n    \n    Critérios de Aceite:\n    - Usuário deve ser direcionado ao dashboard.\n    - Navbar ou similar deve exibir que o usuário está logado (ex.: \"Logout\").\n    ", "steps": [{"name": "Make request to Faker API: http://faker:5000/generate/user", "status": "passed", "start": 1740707548580, "stop": 1740707548584}], "attachments": [{"name": "test_credentials", "source": "bcd1baa0-c061-400b-89c0-dcd441897d96-attachment.txt", "type": "text/plain"}, {"name": "login_page_valid_creds_test", "source": "85a1b958-1c96-4c69-9f00-c76009525294-attachment.png", "type": "image/png"}, {"name": "after_valid_login_attempt", "source": "d8c274ad-88c5-405d-a0aa-d5d7d1609386-attachment.png", "type": "image/png"}, {"name": "log", "source": "11e3aeb1-8f4a-47cd-95e4-c7352b65bfd1-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "5c5a58af-7368-48f5-a278-eda357f8533d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "selenium_browser", "value": "'chrome'"}], "start": 1740707548579, "stop": 1740707549363, "uuid": "e07f5b05-02b3-4c82-9c0b-1f3d8b3509ef", "historyId": "81c82b11884ef8f9f4cf433ef401588b", "testCaseId": "0e01b30eb6581bf5a7b2da883fc13f94", "fullName": "tests.login_credenciais_validas_test#test_login_credenciais_validas", "labels": [{"name": "feature", "value": "Login"}, {"name": "epic", "value": "Authentication"}, {"name": "story", "value": "Valid Credentials"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "nondestructive"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_credenciais_validas_test"}, {"name": "host", "value": "e130d6c28101"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_credenciais_validas_test"}]}