{"uuid": "abce83c1-59e1-492c-800c-b70222d5f361", "children": ["8f6d46fe-1517-4183-9f0f-da2e1f552bb9"], "befores": [{"name": "driver", "status": "failed", "statusDetails": {"message": "Failed: Could not initialize WebDriver for chrome: Message: wait: http://172.17.0.4:4444/ does not respond in 30s\n\n", "trace": "  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/app/conftest.py\", line 96, in driver\n    pytest.fail(f\"Could not initialize WebDriver for {selenium_browser}: {str(e)}\")\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "webdriver_exception_chrome", "source": "adbb7642-04c4-49f4-927c-45065ec0c676-attachment.txt", "type": "text/plain"}], "start": 1740704098730, "stop": 1740704135595}], "start": 1740704098730, "stop": 1740704135597}