{"name": "test_intentional_failure[chrome]", "status": "failed", "statusDetails": {"message": "Failed: Could not initialize WebDriver for chrome: Message: wait: http://172.17.0.4:4444/ does not respond in 30s", "trace": "Traceback (most recent call last):\n  File \"/app/conftest.py\", line 73, in driver\n    driver = WebDriverFactory.create_driver(\n  File \"/app/utils/webdriver_factory.py\", line 167, in create_driver\n    driver = WebDriverFactory._create_chrome_driver(\n  File \"/app/utils/webdriver_factory.py\", line 315, in _create_chrome_driver\n    driver = webdriver.Remote(\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.SessionNotCreatedException: Message: wait: http://172.17.0.4:4444/ does not respond in 30s\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 157, in pytest_runtest_setup\n    item.session._setupstate.setup(item)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 497, in setup\n    raise exc\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 494, in setup\n    col.setup()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 1795, in setup\n    self._request._fillfixtures()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 566, in _fillfixtures\n    item.funcargs[argname] = self.getfixturevalue(argname)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 585, in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 607, in _get_active_fixturedef\n    self._compute_fixture_value(fixturedef)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 693, in _compute_fixture_value\n    fixturedef.execute(request=subrequest)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1069, in execute\n    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/app/conftest.py\", line 96, in driver\n    pytest.fail(f\"Could not initialize WebDriver for {selenium_browser}: {str(e)}\")\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\nFailed: Could not initialize WebDriver for chrome: Message: wait: http://172.17.0.4:4444/ does not respond in 30s"}, "description": "Test that intentionally fails to demonstrate failure handling", "attachments": [{"name": "log", "source": "00def1d7-d09d-4de2-ab0c-7b556b024c3d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "847be970-1b80-404d-92a3-410b8cac64b1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "selenium_browser", "value": "'chrome'"}], "start": 1740703967408, "stop": 1740703967408, "uuid": "1619d376-2ad8-4a7d-a394-eb4913b83cf5", "historyId": "e64799e7b886704d45fa83087fcbd6fa", "testCaseId": "bbe6768e8de2afd3d3c1b7a29ca1394b", "fullName": "tests.basic_test.TestBasic#test_intentional_failure", "labels": [{"name": "story", "value": "Failing Test"}, {"name": "feature", "value": "Basic Test"}, {"name": "severity", "value": "critical"}, {"name": "epic", "value": "Setup Verification"}, {"name": "tag", "value": "nondestructive"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "basic_test"}, {"name": "subSuite", "value": "TestBasic"}, {"name": "host", "value": "33c69f3255ac"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.basic_test"}], "links": [{"type": "issue", "url": "DEMO-1234", "name": "https://example.com/issue/1234"}]}