{"uuid": "f92efe08-6821-46a7-92cf-237bb13a295d", "children": ["e89359fc-baa9-40bc-bff9-38f730aebb1f"], "befores": [{"name": "driver", "status": "failed", "statusDetails": {"message": "Failed: Could not initialize WebDriver for chrome: Message: wait: http://172.17.0.2:4444/ does not respond in 30s\n\n", "trace": "  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/app/conftest.py\", line 96, in driver\n    pytest.fail(f\"Could not initialize WebDriver for {selenium_browser}: {str(e)}\")\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "webdriver_exception_chrome", "source": "2252997e-e33f-4e4b-9b7a-dbd41b7b400c-attachment.txt", "type": "text/plain"}], "start": 1740703930048, "stop": 1740703964451}], "start": 1740703930048, "stop": 1740703964455}