2025-02-28 00:34:25,107 - utils.webdriver_factory - INFO - Creating chrome latest WebDriver with remote=True, remote_url=http://selenoid:4444/wd/hub
2025-02-28 00:34:28,613 - utils.webdriver_factory - WARNING - Error connecting to Selenoid: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /status (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd599d06a10>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
2025-02-28 00:34:28,613 - utils.webdriver_factory - WARNING - Could not verify Selenoid connection at http://selenoid:4444/wd/hub
2025-02-28 00:34:28,613 - utils.webdriver_factory - WARNING - Proceeding anyway, but this might cause issues
2025-02-28 00:34:28,613 - utils.webdriver_factory - INFO - Connecting to Selenoid at http://selenoid:4444/wd/hub with Chrome latest
2025-02-28 00:34:32,126 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd599d05ff0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)")': /wd/hub/session
2025-02-28 00:34:41,590 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd599d05f30>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)")': /wd/hub/session
2025-02-28 00:34:45,085 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd599d05b70>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)")': /wd/hub/session
2025-02-28 00:34:48,500 - utils.webdriver_factory - ERROR - Failed to create Remote WebDriver: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd599d05e10>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
2025-02-28 00:34:51,851 - utils.webdriver_factory - ERROR - Could not get Selenoid status: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /status (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd599d048e0>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
2025-02-28 00:34:51,852 - utils.webdriver_factory - ERROR - Failed to create WebDriver: HTTPConnectionPool(host='selenoid', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd599d05e10>: Failed to resolve 'selenoid' ([Errno -2] Name or service not known)"))
